---

- name: Install lvm and xfs tools
  apt: name={{ item }}
  with_items:
    - xfsprogs 
    - xfsdump 
    - lvm2

- name: create lvm volume group
  lvg: "vg={{ riak_data_lvg }} pvs={{ riak_data_devices|join(',') }}"
- name: create lvm logical volume
  lvol: "vg={{ riak_data_lvg }} size={{ riak_data_volume_size }} lv={{ riak_data_lv }}"
- name: make {{ riak_data_filesystem }} filesystem
  filesystem: "fstype={{ riak_data_filesystem }} dev=/dev/{{ riak_data_lvg }}/{{ riak_data_lv }}"
- name: mount riak data volume
  mount: "src=/dev/{{ riak_data_lvg }}/{{ riak_data_lv }} fstype=xfs name={{ riak_data_mountpoint }} state=mounted"
  