---

- hosts: riak
  become: yes
  gather_facts: no
  roles:
    - init
  tasks:
  - name: Create snapshot of data directory
    command: btrfs subvolume snapshot /var/lib/riak /var/lib/riak/backup_snapshot