---

- hosts: riak
  become: yes
  gather_facts: no
  roles:
    - init
    - riak-server
  vars:
    ring_leader: "riak@{{ riak_ring_leader_host }}"
  tasks:
    - name: Join the cluster
      riak: command=join target_node={{ ring_leader }}
      when: inventory_hostname != riak_ring_leader_host

    - name: Check Riak Ring
      command: 'riak-admin cluster status'
      register: riak_ring_status

    - name: Plan the cluster
      riak: command=plan wait_for_ring=300
      when: riak_ring_status.stdout.find('joining') > 0

    - name: Commit the cluster
      riak: command=commit wait_for_handoffs=300
      when: riak_ring_status.stdout.find('joining') > 0