---

- hosts: riak-test-client
  become: yes
  tasks:
  
  # Install requirements for python test scripts
    - name: Install ansible pip module dependencies
      apt: name={{ item }}
      with_items:
        - build-essential
        - libssl-dev
        - libffi-dev
        - python3-dev
        - python3-pip
    - name: Install riak client for python
      command: pip3 install {{ item }}
      with_items:
        - cryptography
        - riak
        
# Install basho bench tool
    - name: Install some usefull utitlities for basho_bench
      apt: name=realpath
    - name: Download basho bench
      get_url: url=http://ps-tools.s3.amazonaws.com/basho-bench_0.10.0.53.g0e15158-ubuntu14.04LTS-1_amd64.deb dest=/tmp/basho-bench.deb
    - name: Install basho bench
      apt: deb="/tmp/basho-bench.deb"
    - name: Install R and packages required for basho_bench
      apt: name={{ item }}
      with_items:
        - r-base
        - r-base-dev
        - r-cran-plyr
        - r-cran-getopt
        - r-cran-proto
        - r-cran-ggplot2